# Generated by Django 4.2.7 on 2026-01-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='富文本故事内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='entries.entry')),
            ],
            options={
                'verbose_name': '故事',
                'verbose_name_plural': '故事',
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='StoryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stories.story')),
            ],
            options={
                'verbose_name': '故事版本',
                'verbose_name_plural': '故事版本',
                'db_table': 'story_versions',
                'ordering': ['-version_number'],
                'unique_together': {('story', 'version_number')},
            },
        ),
    ]
