# Generated by Django 4.2.7 on 2026-01-22 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('item', '物品'), ('person', '人物')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_method', models.CharField(blank=True, choices=[('purchase', '购买'), ('gift', '礼物'), ('inheritance', '继承'), ('found', '发现'), ('made', '制作'), ('other', '其他')], max_length=20, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('new', '全新'), ('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('importance_score', models.IntegerField(default=5, help_text='1-10分')),
                ('emotional_value', models.IntegerField(default=5, help_text='情感价值 1-10分')),
                ('practical_value', models.IntegerField(default=5, help_text='实用价值 1-10分')),
                ('frequency_of_use', models.IntegerField(default=5, help_text='使用频率 1-10分')),
                ('theme', models.CharField(default='default', max_length=50)),
                ('decorations', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '条目',
                'verbose_name_plural': '条目',
                'db_table': 'entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='entry_media/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='entries.entry')),
            ],
            options={
                'verbose_name': '条目媒体',
                'verbose_name_plural': '条目媒体',
                'db_table': 'entry_media',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
