# Generated by Django 4.2.7 on 2026-01-22 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict, help_text='联系信息'),
        ),
        migrations.AddField(
            model_name='entry',
            name='duration_owned',
            field=models.IntegerField(default=5, help_text='拥有时长重要性 1-10分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='importance_last_evaluated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='layout',
            field=models.CharField(default='default', help_text='布局样式', max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='story_content',
            field=models.TextField(blank=True, help_text='详细故事内容，支持富文本'),
        ),
        migrations.AddField(
            model_name='entry',
            name='story_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='获得日期', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='acquisition_method',
            field=models.CharField(blank=True, choices=[('purchase', '购买'), ('gift', '礼物'), ('inheritance', '继承'), ('found', '发现'), ('made', '制作'), ('other', '其他')], help_text='获得方式', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, help_text='物品类别', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', '全新'), ('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], help_text='物品状况', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(default='CNY', help_text='货币类型', max_length=3),
        ),
        migrations.AlterField(
            model_name='entry',
            name='decorations',
            field=models.JSONField(blank=True, default=list, help_text='装饰元素'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, help_text='简短描述'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='emotional_value',
            field=models.IntegerField(default=5, help_text='情感价值 1-10分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='frequency_of_use',
            field=models.IntegerField(default=5, help_text='使用频率 1-10分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='importance_score',
            field=models.IntegerField(default=5, help_text='综合重要度 1-10分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_private',
            field=models.BooleanField(default=False, help_text='是否私有'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='meeting_date',
            field=models.DateField(blank=True, help_text='认识日期', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='原始价格', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='practical_value',
            field=models.IntegerField(default=5, help_text='实用价值 1-10分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='relationship',
            field=models.CharField(blank=True, choices=[('family', '家人'), ('friend', '朋友'), ('colleague', '同事'), ('mentor', '导师'), ('partner', '伴侣'), ('acquaintance', '熟人'), ('other', '其他')], help_text='关系类型', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='标签列表'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='theme',
            field=models.CharField(default='default', help_text='主题样式', max_length=50),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'type'], name='entries_user_id_fabab4_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'importance_score'], name='entries_user_id_62869e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'created_at'], name='entries_user_id_d630cd_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'updated_at'], name='entries_user_id_fabf0c_idx'),
        ),
    ]
