# Generated by Django 4.2.7 on 2026-01-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('annual_rate', models.DecimalField(decimal_places=4, help_text='年折旧率', max_digits=5)),
                ('min_value_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='最低价值百分比', max_digits=5)),
            ],
            options={
                'verbose_name': '折旧规则',
                'verbose_name_plural': '折旧规则',
                'db_table': 'depreciation_rules',
            },
        ),
        migrations.CreateModel(
            name='ValuationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('category_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('condition_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('age_in_months', models.PositiveIntegerField()),
                ('methodology', models.TextField(help_text='计算方法说明')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='entries.entry')),
            ],
            options={
                'verbose_name': '价值评估记录',
                'verbose_name_plural': '价值评估记录',
                'db_table': 'valuation_records',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
